spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManagement_Db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
SECRET_KEY=2E1uOv9E6zblcNUGWcKpvmkKYI5D6tJ7Rfcd2x2jsnE=